---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: explo-config
  namespace: explo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: large-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: explo-data
  namespace: explo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: large-storage
