apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: zomboid-img-update-auto
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: lag0-fleet-manifests-git
    namespace: flux-system
  git:
    commit:
      messageTemplate: |
        Image update zomboid production.

        Automation name: {{ .AutomationObject }}

        Files:
        {{ range $filename, $_ := .Changed.Files -}}
        - {{ $filename }}
        {{ end -}}

        Objects:
        {{ range $resource, $_ := .Changed.Objects -}}
        - {{ $resource.Kind }} {{ $resource.Name }}
        {{ end -}}

        Images:
        {{ range .Changed.Images -}}
        - {{.}}
        {{ end -}}
      author:
        name: Fluxbot
        email: flux@example.com
    checkout:
      ref:
        branch: main
    push:
      branch: main
