kind: Deployment
apiVersion: apps/v1
metadata:
  name: zomboid-server-1-deployment
  namespace: zomboid-server-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zomboid-server-1
  template:
    metadata:
      name: zomboid-server-1
      namespace: zomboid-server-1
      labels:
        app: zomboid-server-1
    spec:
      nodeSelector:
        kubernetes.io/hostname: ton-cluster-k8s-worker-2
      imagePullSecrets:
      - name: regcred
      initContainers:
      - name: volume-mount-hack
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /home/steam/Zomboid && chown -R 1000:1000 /home/steam/steamcmd/zomboid/steamapps/workshop/content/108600"]
        volumeMounts:
        - name: zomboid-pv-1
          mountPath: /home/steam/Zomboid
        - name: zomboid-mods
          mountPath: /home/steam/steamcmd/zomboid/steamapps/workshop/content/108600
      containers:
      - name: zomboid-server-1-container
        image: placeholder
        env:
          - name: SERVER_NAME
            value: "Lag0 Zomboid"
          - name: ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: zomboid-secrets
                key: admin-password
          - name: PORT
            value: "16261"
          - name: STEAM_PORT1
            value: "16262"
          - name: JAVA_HEAP
            value: "8192m"
          - name: WORKSHOP_IDS
            valueFrom:
              configMapKeyRef:
                name: zomboid-server-1-mods-config
                key: WORKSHOP_IDS
        volumeMounts:
          - name: zomboid-pv-1
            mountPath: /home/steam/Zomboid
          - name: zomboid-mods
            mountPath: /home/steam/steamcmd/zomboid/steamapps/workshop/content/108600
        resources:
          limits:
            cpu: "4"
            memory: 12Gi
          requests:
            cpu: 500m
            memory: 2Gi
        securityContext:
          fsGroup: 1000
          fsGroupChangePolicy: "OnRootMismatch"
      volumes:
      - name: zomboid-pv-1
        persistentVolumeClaim:
          claimName: zomboid-server-1
      - name: zomboid-mods
        persistentVolumeClaim:
          claimName: zomboid-server-mods
