apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: galzolina
resources:
- namespace.yaml
- pvc.yaml
- mariadb-deployment.yaml
- mariadb-service.yaml
- bootstrap-configmap.yaml
- wordpress-deployment.yaml
- wordpress-service.yaml
- virtualservice.yaml
