---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: galzolina-html
  namespace: galzolina
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: large-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: galzolina-db-data
  namespace: galzolina
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: large-storage
