apiVersion: v1
kind: ConfigMap
metadata:
  name: rcon-fix
  namespace: cs16-surf-1
data:
  rcon-fix.pl: |
    use IO::Socket::INET;
    my $s = IO::Socket::INET->new(PeerAddr => '127.0.0.1:27019', Proto => 'udp') or die;
    # Send challenge
    print $s pack('H*', 'ffffffff6368616c6c656e67652072636f6e00');
    $s->recv(my $d, 256);
    $d =~ s/^\x00*//;
    $d =~ /([\d]+)$/;
    my $c = $1;
    # Set bots
    print $s pack('H*', 'ffffffff') . "rcon $c admin123 yb_quota 4\x00";
    $s->recv($d, 256);
    print $s pack('H*', 'ffffffff') . "rcon $c admin123 yb_reset_quota 1\x00";
    $s->recv($d, 256);
    print "Bots configured\n";
