apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cs16-surf-1
resources:
# - configmap-servercfg.yaml
- configmap-image.yaml
- ../../base
replacements:
- source:
    kind: ConfigMap
    name: cs16-surf-image-config
    fieldPath: data.image
  targets:
  - select:
      kind: Deployment
      name: cs16-surf-1-deployment
    fieldPaths:
    - spec.template.spec.containers.[name=cs16-surf-1-container].image
    - spec.template.spec.initContainers.[name=sync-maps].image
    options:
      create: true
patches:
- target:
    kind: Deployment
    name: cs16-surf-1-deployment
  patch: |
    - op: add
      path: /spec/template/spec/containers/0/env
      value:
        - name: PORT
          value: "27019"
        - name: MAX_PLAYERS
          value: "16"
        - name: MAP
          value: "Surf_Style_AKS"
    - op: replace
      path: /spec/template/spec/containers/0/args/0
      value: "sed -i 's/yb_ignore_cvars_on_changelevel.*/yb_ignore_cvars_on_changelevel \"yb_autovacate,yb_chat\"/' /home/steam/steamcmd/cs16/cstrike/addons/yapb/conf/yapb.cfg; echo 'bot_quota 4' >> /home/steam/steamcmd/cs16/cstrike/server.cfg; echo 'yb_quota 4' >> /home/steam/steamcmd/cs16/cstrike/server.cfg; exec /home/steam/steamcmd/cs16/entrypoint.sh"
