apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cs16-surf-1
resources:
- configmap-image.yaml
- configmap-rcon.yaml
- ../../base
replacements:
- source:
    kind: ConfigMap
    name: cs16-surf-image-config
    fieldPath: data.image
  targets:
  - select:
      kind: Deployment
      name: cs16-surf-1-deployment
    fieldPaths:
    - spec.template.spec.containers.[name=cs16-surf-1-container].image
    - spec.template.spec.initContainers.[name=sync-maps].image
    options:
      create: true
patches:
- target:
    kind: Deployment
    name: cs16-surf-1-deployment
  patch: |
    - op: add
      path: /spec/template/spec/containers/0/env
      value:
        - name: PORT
          value: "27019"
        - name: MAX_PLAYERS
          value: "16"
        - name: MAP
          value: "Surf_Style_AKS"
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts
      value:
        - name: rcon-fix
          mountPath: /tmp/rcon-fix
    - op: add
      path: /spec/template/spec/volumes/-
      value:
        name: rcon-fix
        configMap:
          name: rcon-fix
    - op: replace
      path: /spec/template/spec/containers/0/args/0
      value: "/home/steam/steamcmd/cs16/entrypoint.sh & sleep 30 && perl /tmp/rcon-fix/fix-bots.pl 2>&1; wait"
