apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: netbird-management-grpc
  namespace: netbird
  labels:
    kubernetes.io/service-name: netbird-management-grpc
addressType: IPv4
endpoints:
- addresses:
  - 10.244.2.207
  conditions:
    ready: true
ports:
- name: grpc-backcompat
  port: 9996
  protocol: TCP
