apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbird-relay
  namespace: netbird-operator
  labels:
    app: netbird-relay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wg-server
  template:
    metadata:
      labels:
        app: wg-server
    spec:
      containers:
      - name: relay
        image: netbirdio/netbird:0.71.4
        command:
        - netbird
        - relay
        - --listen-address=:3478
        - --exposed-address=$(RELAY_PUBLIC_IP):3478
        - --auth-secret=$(RELAY_SECRET)
        - --enable-stun
        - --stun-ports=3478
        - --log-level=info
        env:
        - name: RELAY_SECRET
          value: "nb-relay-secret-lag0-2026"
        - name: RELAY_PUBLIC_IP
          value: "168.75.108.197"
        ports:
        - containerPort: 3478
          protocol: UDP
        - containerPort: 3478
          protocol: TCP
