apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: netbird
  namespace: netbird-operator
spec:
  hosts:
    - nb.lag0.com.br
    - netbird.lag0.com.br
  gateways:
    - istio-system/lag0-gateway
  http:
    - match:
      - uri:
          prefix: /api/
      route:
      - destination:
          host: netbird-management.netbird.svc.cluster.local
          port:
            number: 80
    - match:
      - uri:
          prefix: /netbird.
      route:
      - destination:
          host: netbird-management.netbird.svc.cluster.local
          port:
            number: 80
    - match:
      - uri:
          prefix: /
      route:
      - destination:
          host: netbird-dashboard.netbird.svc.cluster.local
          port:
            number: 80
