apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: cs16-4fun-img-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: cs16-4fun-img-repo
  filterTags:
    pattern: '^v(\d+\.\d+\.\d+)$'
  policy:
    alphabetical:
      order: asc
