apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-data
  namespace: signoz
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: large-storage
  resources:
    requests:
      storage: 8Gi
