apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: cs-files
  namespace: cs-files
spec:
  hosts:
  - cs-files.lag0.com.br
  gateways:
  - istio-system/lag0-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: cs-files
        port:
          number: 80
