apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: cs-files
  namespace: cs16-surf-1
spec:
  hosts:
  - cs-files.lag0.com.br
  gateways:
  - istio-system/lag0-gateway
  http:
  # Tracker service
  - match:
    - uri:
        prefix: /tracker
    route:
    - destination:
        host: tracker-nginx.tracker.svc.cluster.local
        port:
          number: 80
  # Default: CS files / server page
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: cs16-surf-1.cs16-surf-1.svc.cluster.local
        port:
          number: 80
