---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-db
  namespace: romm
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: large-storage
  resources:
    requests:
      storage: 10Gi
