apiVersion: apps/v1
kind: Deployment
metadata:
  name: conduit
  namespace: matrix
  labels:
    app: conduit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conduit
  template:
    metadata:
      labels:
        app: conduit
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      containers:
      - name: conduit
        image: matrixconduit/matrix-conduit:v0.10.12
        ports:
        - containerPort: 6167
          name: http
        env:
        - name: CONDUIT_CONFIG
          value: /etc/conduit.toml
        volumeMounts:
        - name: config
          mountPath: /etc/conduit.toml
          subPath: conduit.toml
          readOnly: true
        - name: data
          mountPath: /var/lib/matrix-conduit
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
            ephemeral-storage: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
            ephemeral-storage: 512Mi
      volumes:
      - name: config
        configMap:
          name: conduit-config
      - name: data
        persistentVolumeClaim:
          claimName: conduit-data
