apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-cpp
  labels:
    app: llama-cpp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama-cpp
  template:
    metadata:
      labels:
        app: llama-cpp
    spec:
      nodeSelector:
        gpu.amd.com/node: lxc-gpu
      containers:
      - name: llama-cpp
        image: harbor.lag0.com.br/llama-cpp/llama.cpp:vulkan
        ports:
        - containerPort: 8080
        env:
        - name: GGML_VULKAN_DEVICE
          value: "0"
        args: ["--host", "0.0.0.0", "--gpu-layers", "99", "--model", "/models/qwen2.5-7b-instruct-q4_k_m.gguf"]
        volumeMounts:
        - name: models
          mountPath: /models
        - name: dev-dri
          mountPath: /dev/dri
        resources:
          requests:
            memory: "4Gi"
          limits:
            memory: "16Gi"
        securityContext:
          privileged: true
      volumes:
      - name: models
        persistentVolumeClaim:
          claimName: llama-models-pvc
      - name: dev-dri
        hostPath:
          path: /dev/dri
          type: DirectoryOrCreate
