apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-db-init
  namespace: immich
data:
  01-extensions.sql: |
    CREATE EXTENSION IF NOT EXISTS vector;
    CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
    CREATE EXTENSION IF NOT EXISTS cube CASCADE;
    CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;
