apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: matrix
resources:
  - namespace.yaml
  - conduit/configmap.yaml
  - conduit/deployment.yaml
  - conduit/service.yaml
  - synapse/configmap.yaml
  - synapse/postgres.yaml
  - synapse/deployment.yaml
  - element/deployment.yaml
  - element/service.yaml
  - virtualservice.yaml
