apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: netbird-operator
  namespace: netbird-operator
spec:
  interval: 12h
  url: oci://ghcr.io/netbirdio/helm-charts/netbird-operator
  ref:
    semver: "0.6.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbird-operator
  namespace: netbird-operator
spec:
  releaseName: netbird-operator
  targetNamespace: netbird-operator
  install:
    createNamespace: false
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: netbird-operator
  values:
    cluster:
      name: ton
      dns: svc.cluster.local
    netbirdAPI:
      keyFromSecret:
        name: netbird-operator-api-key
        key: NB_API_KEY
    managementURL: http://netbird-management.netbird.svc.cluster.local:80
    routingClientImage: netbirdio/netbird:0.71.4
