---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slskd-config
  namespace: slskd
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: large-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slskd-downloads
  namespace: slskd
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: large-storage
