---
apiVersion: v1
kind: Secret
metadata:
  name: slskd-secrets
  namespace: slskd
type: Opaque
stringData:
  # Soulseek credentials - create an account at https://www.slsknet.org/
  SLSKD_API_KEY: "changethis"
  SLSKD_SLSK_USERNAME: "changethis"
  SLSKD_SLSK_PASSWORD: "changethis"
