apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tracker-data
  namespace: tracker
spec:
  storageClassName: large-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
