apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rotation
resources:
  - namespace.yaml
  - service-account.yaml
  - rbac.yaml
  - cronjob-vw.yaml
  - cronjob-cf.yaml
  - cronjob-netbird.yaml
configMapGenerator:
  - name: rotation-vw
    files:
      - scripts/vw-rotate.sh
  - name: rotation-cf
    files:
      - scripts/cf-rotate.py
  - name: rotation-netbird
    files:
      - scripts/netbird-rotate.py
