apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hermes
resources:
- namespace.yaml
- virtualservice.yaml
- serve-virtualservice.yaml
- hermes/configmap.yaml
- hermes/router-configmap.yaml
- hermes/deployment.yaml
- hermes/service.yaml
- hermes/hub-service.yaml
- hermes/mesh-gateway.yaml
- hermes/pvc.yaml
- hermes/serviceaccount.yaml
- hermes/clusterrolebinding.yaml
- hermes-webui/deployment.yaml
- hermes-webui/service.yaml
- hermes-webui/pvc.yaml
