---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aurral-config
  namespace: aurral
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: large-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aurral-downloads
  namespace: aurral
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: large-storage
