apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: cs16-4fun-1
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: cs16-4fun-mysql
  namespace: cs16-4fun-1
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cs16-4fun-mysql
  serviceName: cs16-4fun-mysql
  template:
    metadata:
      labels:
        app: cs16-4fun-mysql
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: rank_system
        - name: MYSQL_USER
          value: rank_user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-password
              name: cs16-4fun-secrets
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-root-password
              name: cs16-4fun-secrets
        image: mysql:8
        imagePullPolicy: IfNotPresent
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        resources:
          limits:
            cpu: '2'
            memory: 4Gi
          requests:
            cpu: 10m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: large-storage
      volumeMode: Filesystem
    status:
      phase: Pending
