apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zomboid-server-mods
  namespace: zomboid-server-1
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
