apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobilizon
  namespace: mobilizon
  labels:
    app: mobilizon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobilizon
  template:
    metadata:
      labels:
        app: mobilizon
    spec:
      containers:
      - name: mobilizon
        image: framasoft/mobilizon:latest
        ports:
        - containerPort: 4000
        env:
        - name: MOBILIZON_INSTANCE_NAME
          valueFrom:
            secretKeyRef:
              name: mobilizon-secrets
              key: MOBILIZON_INSTANCE_NAME
        - name: MOBILIZON_INSTANCE_HOST
          valueFrom:
            secretKeyRef:
              name: mobilizon-secrets
              key: MOBILIZON_INSTANCE_HOST
        - name: MOBILIZON_INSTANCE_PORT
          valueFrom:
            secretKeyRef:
              name: mobilizon-secrets
              key: MOBILIZON_INSTANCE_PORT
        - name: MOBILIZON_INSTANCE_EMAIL
          valueFrom:
            secretKeyRef:
              name: mobilizon-secrets
              key: MOBILIZON_INSTANCE_EMAIL
        - name: MOBILIZON_REPLY_EMAIL
          valueFrom:
            secretKeyRef:
              name: mobilizon-secrets
              key: MOBILIZON_REPLY_EMAIL
        - name: MOBILIZON_INSTANCE_REGISTRATIONS_OPEN
          valueFrom:
            secretKeyRef:
              name: mobilizon-secrets
              key: MOBILIZON_INSTANCE_REGISTRATIONS_OPEN
        - name: MOBILIZON_DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mobilizon-secrets
              key: POSTGRES_USER
        - name: MOBILIZON_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mobilizon-secrets
              key: POSTGRES_PASSWORD
        - name: MOBILIZON_DATABASE_DBNAME
          valueFrom:
            secretKeyRef:
              name: mobilizon-secrets
              key: POSTGRES_DB
        - name: MOBILIZON_DATABASE_HOST
          value: "mobilizon-postgres-rw"
        - name: MOBILIZON_DATABASE_PORT
          value: "5432"
        - name: MOBILIZON_DATABASE_SSL
          value: "false"
        - name: MOBILIZON_INSTANCE_SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: mobilizon-secrets
              key: MOBILIZON_INSTANCE_SECRET_KEY_BASE
        - name: MOBILIZON_INSTANCE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: mobilizon-secrets
              key: MOBILIZON_INSTANCE_SECRET_KEY
        - name: MOBILIZON_LOGLEVEL
          valueFrom:
            secretKeyRef:
              name: mobilizon-secrets
              key: MOBILIZON_LOGLEVEL
        - name: MOBILIZON_SMTP_SERVER
          valueFrom:
            secretKeyRef:
              name: mobilizon-secrets
              key: MOBILIZON_SMTP_SERVER
        - name: MOBILIZON_SMTP_PORT
          valueFrom:
            secretKeyRef:
              name: mobilizon-secrets
              key: MOBILIZON_SMTP_PORT
        - name: MOBILIZON_SMTP_SSL
          valueFrom:
            secretKeyRef:
              name: mobilizon-secrets
              key: MOBILIZON_SMTP_SSL
        - name: MOBILIZON_SMTP_TLS
          valueFrom:
            secretKeyRef:
              name: mobilizon-secrets
              key: MOBILIZON_SMTP_TLS
        - name: MOBILIZON_SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: mobilizon-secrets
              key: MOBILIZON_SMTP_USERNAME
        - name: MOBILIZON_SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mobilizon-secrets
              key: MOBILIZON_SMTP_PASSWORD
        volumeMounts:
        - name: uploads-storage
          mountPath: /var/lib/mobilizon/uploads
        resources:
          requests:
            memory: "112Mi"
            cpu: "10m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: uploads-storage
        persistentVolumeClaim:
          claimName: mobilizon-uploads-pvc
