apiVersion: v1
kind: Secret
metadata:
  name: mobilizon-postgres-credentials
  namespace: mobilizon
type: kubernetes.io/basic-auth
stringData:
  username: mobilizon
  password: changethis
  database: mobilizon
