apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare-tunnel
data:
  config.yaml: |
    tunnel: nb-mgmt
    credentials-file: /etc/cloudflared/creds/credentials.json
    ingress:
      - hostname: "netbird.lag0.com.br"
        service: tcp://netbird-management.netbird.svc.cluster.local:80
      - hostname: "nb.lag0.com.br"
        service: http://netbird-management.netbird.svc.cluster.local:80
      - hostname: "*.lag0.com.br"
        service: http://istio-gateway.istio-system.svc.cluster.local:80
      - service: http_status:404
