apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-credentials
  namespace: cloudflare-tunnel
type: Opaque
stringData:
  credentials.json: |
    {
      "AccountTag": "c1cc5014eef16759e267a5d4f8254d4d",
      "TunnelID": "6f50e834-7f17-4cc4-82ff-29ce2c3f5cf5",
      "TunnelSecret": "OTc1MTM5MjEtODU2My00YWNiLTlhNDEtZjk0MDgwMGIzYWQ2"
    }
