apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: technitium-netbird-state
  namespace: technitium-dns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: large-storage
