apiVersion: v1
kind: ConfigMap
metadata:
  name: cs16-surf-image-config
  namespace: cs16-4fun-1
data:
  image: harbor.lag0.com.br/library/cs16-surf-server-1:v1.9.8 # {"$imagepolicy": "flux-system:cs16-surf-img-policy"}
  image-version: v1.9.8 # {"$imagepolicy": "flux-system:cs16-surf-img-policy:tag"}
