apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cs16-4fun-1
resources:
# - configmap-servercfg.yaml
- configmap-image.yaml
- configmap-rcon.yaml
- ../../base
replacements:
- source:
    kind: ConfigMap
    name: cs16-surf-image-config
    fieldPath: data.image
  targets:
  - select:
      kind: Deployment
      name: cs16-4fun-1-deployment
    fieldPaths:
    - spec.template.spec.containers.[name=cs16-4fun-1-container].image
    - spec.template.spec.initContainers.[name=sync-maps].image
    options:
      create: true
patches:
- target:
    kind: Deployment
    name: cs16-4fun-1-deployment
  patch: |
    - op: add
      path: /spec/template/spec/containers/0/env
      value:
        - name: PORT
          value: "27018"
        - name: MAX_PLAYERS
          value: "32"
        - name: MAP
          value: "de_dust2"
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/-
      value:
        name: rcon-fix
        mountPath: /tmp/rcon-fix
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/-
      value:
        name: rcon-pass
        mountPath: /tmp/rcon-pass
        readOnly: true
    - op: add
      path: /spec/template/spec/volumes/-
      value:
        name: rcon-fix
        configMap:
          name: rcon-fix
    - op: add
      path: /spec/template/spec/volumes/-
      value:
        name: rcon-pass
        secret:
          secretName: cs16-rcon
    - op: replace
      path: /spec/template/spec/containers/0/args/0
      value: "echo 'setmaster add hl2master.steampowered.com:27011' >> /home/steam/steamcmd/cs16/cstrike/server.cfg && /home/steam/steamcmd/cs16/entrypoint.sh & sleep 45 && perl /tmp/rcon-fix/fix-bots.pl 2>&1; wait"
