apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: netbird
  namespace: netbird
spec:
  interval: 24h
  url: https://netbirdio.github.io/helms
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbird
  namespace: netbird
spec:
  releaseName: netbird
  targetNamespace: netbird
  install:
    createNamespace: true
  interval: 30m
  chart:
    spec:
      chart: netbird
      sourceRef:
        kind: HelmRepository
        name: netbird
        namespace: netbird
      version: 1.9.0
      interval: 12h
  values:
    relay:
      enabled: false
    signal:
      enabled: true
    management:
      podCommand:
        args:
          - --port=80
          - --log-file=console
          - --log-level=info
          - --disable-anonymous-metrics=false
          - --single-account-mode-domain=netbird.lag0.com.br
          - --dns-domain=netbird.lag0.com.br
      configmap: |-
        {
          "Stuns": [
            {
              "Proto": "udp",
              "URI": "stun:stun.l.google.com:19302",
              "Username": "",
              "Password": ""
            }
          ],
          "Signal": {
            "Proto": "http",
            "URI": "netbird-signal:80",
            "Username": "",
            "Password": ""
          },
          "ReverseProxy": {
            "TrustedHTTPProxies": [],
            "TrustedHTTPProxiesCount": 0,
            "TrustedPeers": ["0.0.0.0/0"]
          },
          "Datadir": "/var/lib/netbird/",
          "DataStoreEncryptionKey": "{{ .DATASTORE_ENCRYPTION_KEY }}",
          "StoreConfig": {
            "Engine": "sqlite"
          },
          "HttpConfig": {
            "AuthIssuer": "https://id.lag0.com.br",
            "AuthKeysLocation": "https://id.lag0.com.br/.well-known/jwks.json",
            "OIDCConfigEndpoint": "https://id.lag0.com.br/.well-known/openid-configuration"
          }
        }
      envFromSecret:
        DATASTORE_ENCRYPTION_KEY: netbird-management/datastoreEncryptionKey
      persistence:
        enabled: true
        size: 10Mi
    dashboard:
      env:
        NETBIRD_MGMT_API_ENDPOINT: "https://netbird.lag0.com.br"
        NETBIRD_MGMT_GRPC_API_ENDPOINT: "https://netbird.lag0.com.br"
        AUTH_CLIENT_ID: "netbird-dashboard"
        AUTH_AUTHORITY: "https://id.lag0.com.br"
        AUTH_REDIRECT_URI: "https://netbird.lag0.com.br"
        USE_AUTH0: "false"
        AUTH_SUPPORTED_SCOPES: "openid profile email groups"
        LETSENCRYPT_DOMAIN: "none"
        NGINX_SSL_PORT: "443"
    ingress:
      management:
        enabled: false
      signal:
        enabled: false
      relay:
        enabled: false
      dashboard:
        enabled: false
