kind: Deployment
apiVersion: apps/v1
metadata:
  name: cs16-4fun-1-deployment
  namespace: cs16-4fun-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cs16-4fun-1
  template:
    metadata:
      name: cs16-4fun-1
      namespace: cs16-4fun-1
      labels:
        app: cs16-4fun-1
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: cs16-4fun-1-container
        ports:
        - name: udp-27020
          containerPort: 27020
          protocol: UDP
        image: placeholder
        command: ["/bin/bash", "-c"]
        args:
        - "/home/steam/steamcmd/cs16/entrypoint.sh"
        env:
        - name: PORT
          value: "27020"
        - name: MAX_PLAYERS
          value: "20"
        - name: MAP
          value: "de_dust2"
        - name: MYSQL_HOST
          value: "cs16-4fun-mysql"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: "rank_user"
        - name: MYSQL_DATABASE
          value: "rank_system"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cs16-4fun-secrets
              key: mysql-password
        resources:
          limits:
            cpu: "4"
            memory: 12Gi
          requests:
            cpu: 10m
            memory: 64Mi
