kind: Service
apiVersion: v1
metadata:
  name: cs16-4fun-1
  namespace: cs16-4fun-1
  labels:
    app: cs16-4fun-1
spec:
  type: ClusterIP
  selector:
    app: cs16-4fun-1
  ports:
  - name: udp-27018
    port: 27018
    targetPort: 27018
    protocol: UDP
  - name: http-maps
    port: 80
    targetPort: 80
    protocol: TCP
