apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-zookeeper
provisioner: nfs.csi.k8s.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.2
  - async
  - anonuid=1001
  - anongid=1001
  - noatime
parameters:
  server: 192.168.88.245
  share: /ton-cluster
  subDir: ${pvc.metadata.namespace}_${pvc.metadata.name}
